vim.o.nu = true
vim.o.rnu = true
vim.o.smd = false
vim.o.tabstop = 4
--vim.o.mouse = 'a'
vim.o.scrolloff = 8
vim.o.shiftwidth = 0
vim.g.mapleader = ","
vim.o.softtabstop = -1
vim.o.undofile = true
vim.o.expandtab = true
vim.o.smartcase = true
vim.o.ignorecase = true
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.fillchars = 'fold: '
vim.o.clipboard = 'unnamedplus'
vim.o.undodir = '/home/estatuadetamal/.cache/nvim/undo-dir/'
--vim.o.termguicolors = true
--require'colorizer'.setup()
