local function map(m, k, v)
    vim.keymap.set(m, k, v, { silent = true })
end
map('n', '<leader>o', 'o<ESC>')
map('n', '<leader>O', 'O<ESC>')
map('', '<leader>h', '<C-w>h')
map('', '<leader>j', '<C-w>j')
map('', '<leader>k', '<C-w>k')
map('', '<leader>l', '<C-w>l')
map('n', '<C-j>', '<CMD>move .+1<CR>')
map('n', '<C-k>', '<CMD>move .-2<CR>')
map('x', '<C-j>', ":move '>+1<CR>gv=gv")
map('x', '<C-k>', ":move '<-2<CR>gv=gv")
map( 'i',':w', '<Esc>:w<CR>')
map( 't','<Esc>', '<C-\\><C-n>')

map( 'i','<leader>ñ', '<++>')
map( 'n','<leader>ñ', 'i<++><Esc>')
map( '','<leader><leader>', '<Esc>/<++><Enter>"_c4l')
map('','<F1>' , ':setlocal spell! spelllang=es_es,en_gb<CR>')
map('','<F2>' , ':setlocal spell! spelllang=es_es<CR>')
map('','<F3>' , ':setlocal spell! spelllang=en_gb<CR>')
map('','<F12>', ':vsp /home/estatuadetamal/.config/nvim/init.lua<CR><CR>')
